using System.Collections.Generic;

namespace BigAmbitions.SaveSystem.Legacy;

public sealed class TransactionLegacyMap : LegacyMapperBase
{
	public override List<string> Keys => new List<string> { "Transaction.transactionType", "HasEarnedMoney.transactionTypes", "HasTransactionType.transactionType", "PaidActivityEnvironment.transactionType" };

	protected override Dictionary<int, string> Map => new Dictionary<int, string>
	{
		{ 1, "ba:transaction_rent" },
		{ 2, "ba:transaction_wage" },
		{ 3, "ba:transaction_revenue" },
		{ 4, "ba:transaction_loanpayout" },
		{ 5, "ba:transaction_parkingticket" },
		{ 6, "ba:transaction_depositreturn" },
		{ 7, "ba:transaction_playerjobsalary" },
		{ 8, "ba:transaction_cleaningwage" },
		{ 9, "ba:transaction_unassignedwage" },
		{ 10, "ba:transaction_marketing" },
		{ 11, "ba:transaction_cheat" },
		{ 12, "ba:transaction_subwayride" },
		{ 13, "ba:transaction_recruitmentcampaign" },
		{ 14, "ba:transaction_importdelivery" },
		{ 15, "ba:transaction_importdeliveryrefund" },
		{ 16, "ba:transaction_deliverycontract" },
		{ 17, "ba:transaction_deliverycontractrefund" },
		{ 18, "ba:transaction_itempurchase" },
		{ 19, "ba:transaction_loanpayment" },
		{ 20, "ba:transaction_loanpayoff" },
		{ 21, "ba:transaction_tuitionfee" },
		{ 22, "ba:transaction_deposit" },
		{ 23, "ba:transaction_depositreturnfurniture" },
		{ 24, "ba:transaction_employeetraining" },
		{ 25, "ba:transaction_itemsold" },
		{ 26, "ba:transaction_vehiclebought" },
		{ 27, "ba:transaction_taxiride" },
		{ 28, "ba:transaction_hospitalbill" },
		{ 29, "ba:transaction_buildingbought" },
		{ 30, "ba:transaction_rentrevenue" },
		{ 31, "ba:transaction_autotowservice" },
		{ 32, "ba:transaction_taxpayment" },
		{ 33, "ba:transaction_buildingsold" },
		{ 34, "ba:transaction_publicparking" },
		{ 35, "ba:transaction_casino" },
		{ 36, "ba:transaction_casinoboatticket" },
		{ 37, "ba:transaction_hrtraining" },
		{ 38, "ba:transaction_replacementwage" },
		{ 39, "ba:transaction_investment" },
		{ 40, "ba:transaction_investmentpayout" },
		{ 41, "ba:transaction_banknegativeinterestrate" },
		{ 42, "ba:transaction_interiordesigner" },
		{ 43, "ba:transaction_furniturerecolor" },
		{ 44, "ba:transaction_boatbought" },
		{ 45, "ba:transaction_boatyearlymaintenance" },
		{ 46, "ba:transaction_boatsold" },
		{ 47, "ba:transaction_doctorappointment" },
		{ 48, "ba:transaction_compatibilityfix" },
		{ 49, "ba:transaction_furnituredeliveryrefund" },
		{ 50, "ba:transaction_gymentrance" },
		{ 51, "ba:transaction_healthinsurance" },
		{ 52, "ba:transaction_entrancefee" },
		{ 53, "ba:transaction_electricscooterfee" },
		{ 54, "ba:transaction_interiorinstallation" },
		{ 55, "ba:transaction_replacementfee" },
		{ 56, "ba:transaction_employeebonus" },
		{ 57, "ba:transaction_movingservice" },
		{ 58, "ba:transaction_deliveryjobwage" },
		{ 59, "ba:transaction_businessinventorysold" },
		{ 60, "ba:transaction_cargoholderinventorysold" },
		{ 61, "ba:transaction_pierride" },
		{ 62, "ba:transaction_licensingfee" },
		{ 63, "ba:transaction_donation" },
		{ 64, "ba:transaction_exportedgoods" },
		{ 65, "ba:transaction_purchasefromsellerstand" },
		{ 66, "ba:transaction_purchaseattractionticket" }
	};
}
